export const REASON_CODES = [
  'APPLIED',
  'IDENTITY_SELECTED',
  'PROTECTED_ROLE',
  'PROTECTED_KIND',
  'ROLE_PROVENANCE_INVALID',
  'SHADOW_ONLY',
  'NO_ELIGIBLE_CODEC',
  'CODEC_NOT_REGISTERED',
  'CODEC_NOT_APPLICABLE',
  'TOKENIZER_UNAVAILABLE',
  'TOKENIZER_NOT_EXACT',
  'TOKENIZER_ERROR',
  'NO_SAVINGS',
  'BELOW_MIN_SAVINGS',
  'DECODER_OVERHEAD_EXCEEDS_SAVINGS',
  'FORMAT_UNSUPPORTED',
  'ANCHOR_INVALID',
  'ANCHOR_OVERLAP',
  'ANCHOR_MISSING',
  'ANCHOR_MUTATED',
  'ANCHOR_REORDERED',
  'PROTECTED_ANCHOR',
  'INPUT_TOO_LARGE',
  'OUTPUT_EXPANSION',
  'CODEC_TIMEOUT',
  'CODEC_ERROR',
  'CODEC_VERSION_MISMATCH',
  'POLICY_DIGEST_MISMATCH',
  'ORIGINAL_HASH_MISMATCH',
  'ENCODED_HASH_MISMATCH',
  'ENCODER_MISMATCH',
  'PROOF_DIGEST_MISMATCH',
  'ROUNDTRIP_MISMATCH',
  'TYPED_AST_MISMATCH',
  'CAS_WRITE_FAILED',
  'CAS_MISS',
  'CAS_CORRUPT',
  'DECODE_LIMIT',
  'MALFORMED_ENVELOPE',
  'FALLBACK_ORIGINAL',
] as const;

export type ReasonCode = (typeof REASON_CODES)[number];

const REASON_CODE_SET: ReadonlySet<string> = new Set(REASON_CODES);

export function isReasonCode(value: unknown): value is ReasonCode {
  return typeof value === 'string' && REASON_CODE_SET.has(value);
}
